todo_project/todo/urls.py
from django.urls import path
from . import views
app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    path('todo/', views.todoappView, name='todo'),
    path('addTodoItem/',views.addTodoView), 
    path('deleteTodoItem/<int:i>/', views.deleteTodoView), 
] 

todo_project/todo_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls',)),
    path('', include('userauth.urls',)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo_project/userauth/urls.py
from django.urls import path
from . import views
app_name = 'userauth'
urlpatterns = [
    path('login/', views.t_login, name='login'),
    path('signup/',views.t_sign_up, name='signup'),
    path('logout/',views.logoutUser,name='logout')
] 

todo_project/todo/models.py
from django.db import models
from django.utils import timezone
 
# Create your models here.
class TodoListItem(models.Model):
    content = models.TextField() 
    date=models.DateField(auto_now_add=True)
    user=models.CharField(max_length=100)
    
# Create your models here.

todo_project/userauth/models.py
from django.db import models

# Create your models here.

todo_project/todo/views.py
from django.shortcuts import render
from .models import TodoListItem 
from django.http import HttpResponseRedirect 

from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request, 'index.html')


@login_required(login_url='/login')
def todoappView(request):
    
    user_email = request.user.email
    # all_todo_items = TodoListItem.objects.all()
    all_todo_items = TodoListItem.objects.filter(user=user_email)
    return render(request, 'todolist.html',  {'all_items':all_todo_items})

@login_required(login_url='/login')
def addTodoView(request):
    # x = request.POST.get('todotext')
    user_email = request.user.email
    new_item = TodoListItem()
    new_item.user = user_email
    new_item.content = request.POST.get('content')
    new_item.save()
    return HttpResponseRedirect('/todo/') 
    
@login_required(login_url='/login')
def deleteTodoView(request, i):
    y = TodoListItem.objects.get(id= i)
    y.delete()
    return HttpResponseRedirect('/todo/') 


from django.shortcuts import render, redirect

todo_project/userauth/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# from .models import users

from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User

from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages

from django.contrib.auth.decorators import login_required

from .models import *
# from .forms import CreateUserForm
# Create your views here.


def t_sign_up(request):
    if request.user.is_authenticated:
        return redirect('/todo')
    else:
        if request.method == 'POST':
            if request.POST['nPassword1'].strip() == request.POST['nPassword2'].strip():
                user = User(password=make_password(request.POST['nPassword1'].strip()),
                            username=request.POST['nEmail'],
                            email=request.POST['nEmail'])
                user.save()
                # userdetails = f_users(user_name=user.username, email=user.email,
                #                           mobile_number=request.POST['nPhone'], user_id=user)
                # userdetails = f_users(user_Id=user, user_Email=user.email)
                # userdetails.save()
                return redirect('userauth:login')
            else:
                context = {
                    'msg': 'Error in the inputs given, kindly make sure that you are using proper details to create user'
                }
                return render(request, 'signup.html', context)
        context = {
            'msg': ''
        }
        return render(request, 'signup.html', context)


def t_login(request):
	if request.user.is_authenticated:
		return redirect('/todo')
	else:
		if request.method == 'POST':
			Email = request.POST.get('email_address')
			password =request.POST.get('password')
			user = authenticate(request, username=Email, password=password)

			if user is not None:
				login(request, user)
				if 'next' in request.POST:
					return redirect(request.POST.get('next'))
				# elif user.is_staff == 1:
				# 	return redirect('main:admin_dashboard')
				else:
					return redirect('todo:todo')
			else:
				print('Login is not success')
				# messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'login.html', context)

def logoutUser(request):
	logout(request)
	return redirect('/login')

todo_project/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <!-- CSS only -->
    <link rel="stylesheet" type="text/css" href="{%static 'Mainpage.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <title>Venue Booking</title>
</head>
<body style="background-color:rgb(241, 230, 206);">
    
<div class="container" >
    <!-- <div class="row">
      <img src="{% static 'img\images(1).png'%}" alt="" class="img-fluid mx-auto d-block float-center r-50" style="width: 650px; height:350px;">
    </div> -->
    <!-- <img src="{% static 'todo_project\static\img\pic.png' %}" -->
    <div class="card text-center" style="margin-top: 200px; background-color: rgb(255, 251, 242);" >
       
        <div class="card-body">
          <h5 class="card-title">Welcome to the Filna Venue Booking</h5>
          <p class="card-text">Make Your Destinations Beautiful</p>
          <a href="{% url 'todo:todo' %}" class="btn btn-primary">Login In!</a>
          
        </div>
        <div class="card-footer text-muted">
          
        </div>
      </div>
</div>

    
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>    
</body>
</html>

todo_project/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <!-- CSS only -->
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>LOGIN</title>
</head>
<body>
    
  
    <section class="vh-100" style="background-color: rgb(255, 255, 255);">
        <div class="container h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
              <div class="card text-black" style="border-radius: 25px; background-color: rgb(228, 214, 187);">
                <div class="card-body p-md-5">
                  <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
      
                      <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Login</p>
      
                      <form class="mx-1 mx-md-4" method="post">
                        {% csrf_token %}
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="email_address">Your Email</label>
                            <input type="email" name="email_address" id="email_address" class="form-control" />
                          </div>
                        </div>
      
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="password">Password</label>
                            <input type="password" id="password" name="password" class="form-control" />
                          </div>
                        </div>

      
                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                          <button type="submit" class="btn btn-primary btn-lg">Login</button>
                        </div>
      
                      </form>
      
                      <h6 class="text-center mt-1" style="color: var(--light-black);">Dont have an account <a href="{% url 'userauth:signup' %}" style="color:black ;"><u>Sign Up</u></a> now!</h6>

                    </div>
                    <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
      
                      <img src="{% static 'img\loginpage.jpg'%}" alt="" class="img-fluid mx-auto d-block float-center r-50" style="width: 650px; height:350px;">
                         
      
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>




      <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

todo_project/templates/mainpage.html
<!DOCTYPE html>
<html>
<head>
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
<title>Venue Booking Application</title>
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

body {
  font-family: Arial, Helvetica, sans-serif;
  background-color: beige;
}

/* Float four columns side by side */
.column {
  float: left;
  width: 25%;
  padding: 0 10px;
}

/* Remove extra left and right margins, due to padding */
.row {margin: 0 -5px;}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive columns */
@media screen and (max-width: 600px) {
  .column {
    width: 100%;
    display: block;
    margin-bottom: 20px;
  }
}

/* Style the counter cards */
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  padding: 16px;
  text-align: center;
  background-color: #f1f1f1;
}
.btn btn-primary{
  background-color: beige;
}
</style>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">
          <img src="{%static 'img\images.png'%}" width="130" height="30" class="d-inline-block align-top" alt="">
          
        </a>
      </nav>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="https://book.bwhhotelgroup.com/content/ibe-86070/en_US/booking-path/hotel-rooms.86070.html">Reservation <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://www.gulfhotelbahrain.com/superior-rooms">Accomodation</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="https://www.gulfhotelbahrain.com/prestige_club">VIP Club</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.gulfhotelbahrain.com/contact-us">Contact</a>
          </li>
          
        
      </ul>
      
    </div>
  </nav>
</div>


<br>
<div class="row">
    <div class="card" style="width: 18rem;margin:1rem">
      
        <img class="card-img-top" src="{% static 'img\image1.jpg'% }" alt="Card image cap">
        <h4>Luxurious Hall</h4>
        <div class="card-body">
          <p class="card-text">Luxurious Venue for Marriage Functions Available, with seating around 500 people. To book please click.</p>
          <a href="#" class="btn btn-primary">Click On</a>
        </div>
      </div>
      <br>
      

  <div class="card" style="width: 18rem;margin:1rem">
    <img class="card-img-top" src="{% static 'img\image1.jpg'% }" alt="Card image cap">
    <h4>General Hall</h4>
    <div class="card-body">
      <p class="card-text">Luxurious Venue for Marriage Functions Available, with seating around 500 people. To book please click.</p>
      <a href="#" class="btn btn-primary">Click On</a>
    </div>
  </div>
  <br>
  <div class="card" style="width: 18rem;margin:1rem">
    <img class="card-img-top" src="{% static 'img\image2.jpg'% }" alt="Card image cap">
    <h4>Designful Hall</h4>
    <div class="card-body">
      <p class="card-text">Luxurious Venue for Marriage Functions Available, with seating around 500 people. To book please click.</p>
      <a href="#" class="btn btn-primary">Click On</a>
    </div>
  </div>
  <br>
  <div class="card" style="width: 18rem;margin:1rem">
    <img class="card-img-top" src="{% static 'img\image3.jpg'% }" alt="Card image cap">
    <h4>Banquet Hall</h4>
    <div class="card-body">
      <p class="card-text">Luxurious Venue for Marriage Functions Available, with seating around 500 people. To book please click.</p>
      <a href="#" class="btn btn-primary">Click On</a>
    </div>
  </div>
  <div class="row">
    <div class="card" style="width: 18rem;margin:1rem">
      
        <img class="card-img-top" src="{% static 'img\path.jpg'% }" alt="Card image cap">
        <h4>Pathway Hall</h4>
        <div class="card-body">
          <p class="card-text">Luxurious Venue for Marriage Functions Available, with seating around 500 people. To book please click.</p>
          <a href="#" class="btn btn-primary">Click On</a>
        </div>
      </div>
      <br>
      

  <div class="card" style="width: 18rem;margin:1rem">
    <img class="card-img-top" src="{% static 'img\seminar.jpg'% }" alt="Card image cap">
    <h4>Seminar Hall</h4>
    <div class="card-body">
      <p class="card-text">Luxurious Venue for Marriage Functions Available, with seating around 500 people. To book please click.</p>
      <a href="#" class="btn btn-primary">Click On</a>
    </div>
  </div>
  <br>
  <div class="card" style="width: 18rem;margin:1rem">
    <img class="card-img-top" src="{% static 'img\meeting.jpg'% }" alt="Card image cap">
    <h4>Meeting Hall</h4>
    <div class="card-body">
      <p class="card-text">Luxurious Venue for Marriage Functions Available, with seating around 500 people. To book please click.</p>
      <a href="#" class="btn btn-primary">Click On</a>
    </div>
  </div>
  <br>
  <div class="card" style="width: 18rem;margin:1rem">
    <img class="card-img-top" src="{% static 'img\seperate.jpg'% }" alt="Card image cap">
    <h4>Seperate Hall for Male and Female</h4>
    <div class="card-body">
      <p class="card-text">Luxurious Venue for Marriage Functions Available, with seating around 500 people. To book please click.</p>
      <a href="#" class="btn btn-primary">Click On</a>
    </div>
  </div>

</body>
</html>

todo_project/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Signup</title>
</head>
<body>
    

    <section class="vh-100" style="background-color: #eee;">
        <div class="container h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
              <div class="card text-black" style="border-radius: 25px;">
                <div class="card-body p-md-5">
                  <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
      
                      <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
      
                      <form class="mx-1 mx-md-4" method="post">
                        {% csrf_token %}
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="nUsername">User Name</label>
                            <input type="text" name="nUsername" id="nUsername" class="form-control" />
                          </div>
                        </div>
      
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="nEmail">Your Email</label>
                            <input type="email" name="nEmail" id="nEmail" class="form-control" />
                          </div>
                        </div>
      
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="nPassword1">Password</label>
                            <input type="password" name="nPassword1" id="nPassword1" class="form-control" />
                          </div>
                        </div>
      
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-key fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="nPassword2">Repeat your password</label>
                            <input type="password" name="nPassword2" id="nPassword2" class="form-control" />
                          </div>
                        </div>
      
      
                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                          <button type="submit" class="btn btn-primary btn-lg">Register</button>
                        </div>
      
                      </form>
      
                      <h6 class="text-center mt-1" style="color: var(--light-black);">Already have an account? <a href="{% url 'userauth:login' %}" style="color:black ;"><u>Login</u></a> now!</h6>


                    </div>
                    <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
      
                      <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                        class="img-fluid" alt="Sample image">
      
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>




      <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>